FROM python:3-alpine

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN apk add alpine-sdk libffi-dev zlib-dev jpeg-dev git bash perl
RUN pip install --no-cache-dir -r requirements.txt
COPY ./src ./src
CMD [ "python", "./src/main.py" ]